import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    q: "Who owns the chargers?",
    a: "UbiqPower owns the charging stations for the duration of the agreement. At the end of the term, the strata or building owner may have the option to purchase the equipment or extend the agreement.",
  },
  {
    q: "Who pays the electricity bill?",
    a: "Electricity costs for EV charging are billed through BC Hydro and handled through the strata corporation or property owner as part of the program arrangement.",
  },
  {
    q: "How many chargers can we receive?",
    a: "UbiqPower determines the number of chargers based on electrical capacity, number of EV drivers, site readiness, and minimum charging thresholds.",
  },
  {
    q: "What about carbon credits?",
    a: "Carbon credits generated by the charging activity are retained by UbiqPower for the duration of the agreement.",
  },
  {
    q: "What types of properties are eligible?",
    a: "Multi-family residential buildings, strata corporations, commercial buildings, retail properties, and similar properties may qualify.",
  },
  {
    q: "Is approval guaranteed?",
    a: "No. Acceptance into the Zero Cost EV Charger Program is subject to UbiqPower's site review and approval.",
  },
];

export function FAQ() {
  return (
    <section id="faq" className="bg-background pb-20 pt-10 md:pb-28 md:pt-14">
      <div className="mx-auto max-w-[1380px] px-5 md:px-8">
        <div className="grid gap-12 lg:grid-cols-12">
          <div className="lg:col-span-4">
            <h2 className="text-3xl font-semibold tracking-tight text-foreground md:text-4xl lg:text-5xl">
              FAQ
            </h2>
            <p className="mt-5 text-muted-foreground">
              Common questions about the Zero Cost EV Charger Program. Reach out for anything we
              have not covered.
            </p>
          </div>

          <div className="lg:col-span-8">
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((f, i) => (
                <AccordionItem key={i} value={`item-${i}`} className="border-b border-neutral-300">
                  <AccordionTrigger className="py-5 text-left text-base font-semibold text-foreground hover:no-underline md:text-lg">
                    {f.q}
                  </AccordionTrigger>
                  <AccordionContent className="text-sm leading-relaxed text-muted-foreground md:text-base">
                    {f.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </div>
      </div>
    </section>
  );
}
