/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsL3FastDcEvChargerRouteImport } from './routes/products/l3-fast-dc-ev-charger'
import { Route as ProductsL2EvChargerRouteImport } from './routes/products/l2-ev-charger'

const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsL3FastDcEvChargerRoute =
  ProductsL3FastDcEvChargerRouteImport.update({
    id: '/products/l3-fast-dc-ev-charger',
    path: '/products/l3-fast-dc-ev-charger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsL2EvChargerRoute = ProductsL2EvChargerRouteImport.update({
  id: '/products/l2-ev-charger',
  path: '/products/l2-ev-charger',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/products/l2-ev-charger': typeof ProductsL2EvChargerRoute
  '/products/l3-fast-dc-ev-charger': typeof ProductsL3FastDcEvChargerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/products/l2-ev-charger': typeof ProductsL2EvChargerRoute
  '/products/l3-fast-dc-ev-charger': typeof ProductsL3FastDcEvChargerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/products/l2-ev-charger': typeof ProductsL2EvChargerRoute
  '/products/l3-fast-dc-ev-charger': typeof ProductsL3FastDcEvChargerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/products/l2-ev-charger'
    | '/products/l3-fast-dc-ev-charger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/products/l2-ev-charger'
    | '/products/l3-fast-dc-ev-charger'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/products/l2-ev-charger'
    | '/products/l3-fast-dc-ev-charger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  ProductsL2EvChargerRoute: typeof ProductsL2EvChargerRoute
  ProductsL3FastDcEvChargerRoute: typeof ProductsL3FastDcEvChargerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/l3-fast-dc-ev-charger': {
      id: '/products/l3-fast-dc-ev-charger'
      path: '/products/l3-fast-dc-ev-charger'
      fullPath: '/products/l3-fast-dc-ev-charger'
      preLoaderRoute: typeof ProductsL3FastDcEvChargerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/l2-ev-charger': {
      id: '/products/l2-ev-charger'
      path: '/products/l2-ev-charger'
      fullPath: '/products/l2-ev-charger'
      preLoaderRoute: typeof ProductsL2EvChargerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  ProductsL2EvChargerRoute: ProductsL2EvChargerRoute,
  ProductsL3FastDcEvChargerRoute: ProductsL3FastDcEvChargerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
